### ISSUE TITLE
Tests fail with Babel plugin error

### ISSUE THREAD

**Issue by kaitmore** [Cretezy/Noderize#13]
### What version of Noderize and Node are you using?
Node v9.4.0 
Noderize v0.5.0

### What operating system are you using? Are you using any special setup?
macOS High Sierra

### What did you do?
I created a new project with `npx create-noderize` and set `"languages": "typescript"` within the noderize config field in my package.json. I then created a test file under /src and ran `npm run test`, which gives me the following error: 

```
The new decorators proposal is not supported yet. You must pass the `"legacy": true` 
option to @babel/plugin-proposal-decorators  (While processing: "/node_modules/
@babel/plugin-proposal-decorators/lib/index.js")
```

I also tried adding a babel config within the noderize config in package.json, setting the "legacy": true option for @babel/plugin-proposal-decorators as the error instructed, but that didn't have any effect.

### What did you expect to see?
No errors

### What did you see instead?
![image](https://user-images.githubusercontent.com/22768918/39266111-0f0eb9f0-4897-11e8-8cd8-0f220b13f6ca.png)

**Comment by Cretezy** [comment]
Yep. Just ran into this today. Will have an update soon. Seems like Babel did a breaking change.

**Comment by Cretezy** [comment]
I've forced pushed `0.6.0` which fixes this (and changes to Webpack 4).
