### ISSUE TITLE
[Feature] Use nodejs inspect debugger

### ISSUE THREAD

**Issue by ninox92** [Cretezy/Noderize#21]
When running in development mode it would be nice to be able to attach the [V8 Inspector](https://nodejs.org/api/debugger.html) to the process in order to debug.

**Comment by Cretezy** [comment]
That's a good idea. Will look into it!

**Comment by Cretezy** [comment]
Added to Noderize `v0.7.2`!

Use `--inspect` to enable Node debugger, and `--inspectChrome <port>` to run the DevTools debugger!
