### ISSUE TITLE
running test with --ci

### ISSUE THREAD

**Issue by hobochild** [Cretezy/Noderize#22]
Hey thanks for the project :+1: 

Found a case when running on circle ci, where my tests fail but the process still exits with success code `0`

I'm running `yarn test --ci`

Anyone else encountered this?

**Comment by Cretezy** [comment]
Don't forget to run `yarn bootstrap`! I'll try getting a fix out today

**Comment by Cretezy** [comment]
I've just published `v0.7.1` with this change for the test and format commands, let me know if you encounter any problems!

**Comment by hobochild** [comment]
Works! Thanks for the quick turn around! 🙏

**Comment by Cretezy** [comment]
Thank you! I'd you'll like to vote for Noderize's new logo, look at the "New Logo" issue and click the click in the comments!

Glad I could help you, let me know if anything comes up
