### ISSUE TITLE
Kill child processes on restart

### ISSUE THREAD

**Issue by hobochild** [Cretezy/Noderize#25]
When running in watch mode with an express app every time the server restarts it says there is already something being served on port x. 

Which I assume means the previous process hasn't been completely killed yet? Anyone else encountered this?

**Comment by Cretezy** [comment]
That's odd, it does kill it.

Try using `killall node` and see if it still happens.

**Comment by hobochild** [comment]
Ah that fixed it. I was using `fuser -k`, which solved the issue once but on the watch trigger it would happen again using killall node seems to have fixed it for good. :+1:
