### ISSUE TITLE
Adding Noderize project to Docusaurus user page 🦎

### ISSUE THREAD

**Issue by Rajekevin** [Cretezy/noderize#31]
Hello, 

We would like to add your project to the [Docusaurus users page](https://docusaurus.io/en/users) 
Are you agree for that ?
If yes, are you ok to provide us your logo as well  _(512x512)_ ?

More info about this : [Here](https://github.com/facebook/Docusaurus/issues/1080)
<h1 align="center">
  <p align="center">Docusaurus</p>
  <a href="https://docusaurus.io"><img src="https://docusaurus.io/img/slash-introducing.svg" alt="Docusaurus"></a>
</h1>
Docusaurus is a project for easily building, deploying, and maintaining open source project websites.

**Comment by Cretezy** [comment]
Sure go ahead! You can find the svg logo under docs/website/assets/images I think!
