### ISSUE TITLE
appDirectory not defined

### ISSUE THREAD

**Issue by nvlled** [Cretezy/Noderize#6]
It seems you forgot add this line on start.js
```import { appDirectory } from "../utils/path";```
from this commit https://github.com/Cretezy/Noderize/commit/0f6a90f539c94f81d3c2e2649156c4122be33534#diff-8407c78f3d933d0962c46934b06a4cf6

I'd submit a pull request, but I'm not sure how to build the package.

**Comment by Cretezy** [comment]
https://github.com/Cretezy/Noderize/commit/3e8441b2fb13d08679ee20c2bb7aade3d3daabac

Publishing v0.4.5 after tests run!

**Comment by Cretezy** [comment]
v0.4.5 published!
