### ISSUE TITLE
Error: Can not find jest

### ISSUE THREAD

**Issue by anhnhoktvn** [Cretezy/Noderize#7]
Hi, just try running `npm run test` and found this error:
Error: Cannot find module '/home/user/Documents/dev/test9/node_modules/@noderize/scripts/node_modules/.bin/jest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by Cretezy** [comment]
Can you provide more information about you're setup?
Try deleting node_modules and any lock file and running npm/yarn install

**Comment by anhnhoktvn** [comment]
First I tried with:
```
npx create-noderize test8
cd test8
npm run test
```
it show the same error.
Then I try installing create-noderize as global and create a new project:
```
npm i -g noderize
create-noderize test9
cd test9
npm run test
```
I got the same error

I also tried deleting node_modules as reinstall. Still got the same error.

My OS: Linux mint 18.1
Node version: 8.10.0

**Comment by Cretezy** [comment]
This seems to be a problem with Node's `path.resolve`. I can't replicate it on my machine oddly enough.

It seems to be resolving to `/home/user/Documents/dev/test9/node_modules//node_modules/.bin/jest` instead of `/home/user/Documents/dev/test9/node_modules/.bin/jest` (extra `/node_modules`). 

This is very likely due to npm having `@noderize/scripts` under another level of directory.

Looking for a solution right now, will update when I have more information or a fix.

**Comment by Cretezy** [comment]
Can you provide the version of `@noderize/scripts` in your `package.json`?

Can you also verify if `node_modules/@noderize/scripts/node_modules` exist?

**Comment by anhnhoktvn** [comment]
In package.json:
```
	"devDependencies": {
		"@noderize/scripts": "^0.4.5"
	},
	"dependencies": {
		"@noderize/runtime": "^0.4.5"
	}
```

And the is no `node_modules` folder in the path `node_modules/@noderize/scripts`

**Comment by Cretezy** [comment]
That seems like like path of the issue.

Noderize is looking for `node_modules/@noderize/scripts/node_modules/.bin/jest`, but it cannot find it on your system, which seems like npm isn't linking it.

Which version of npm are you running? Mind upgrading with `npm i -g npm` and seeing if it persists?

**Comment by anhnhoktvn** [comment]
I used npm version 5.4.2. After upgrading to version 5.7.1, removing `node_modules` and `package-lock.json`, reinstall with `npm i` I still got this error.

**Comment by anhnhoktvn** [comment]
I noticed that this time, the error message is a bit different:
```
Error: Cannot find module '/home/user/Documents/dev/test9/node_modules/@noderize/scripts/node_modules/.bin/jest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by anhnhoktvn** [comment]
I tried with a fresh new project 
```
create-noderize test10
cd test10
npm run test
```
and still stuck with this error:
```
Error: Cannot find module '/home/user/Documents/dev/test10/node_modules/@noderize/scripts/node_modules/.bin/jest'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by Cretezy** [comment]
That's very odd. Can you check if `/home/user/Documents/dev/test10/node_modules/@noderize/scripts/node_modules/.bin` exists, and show the contents of `/home/user/Documents/dev/test10/node_modules/.bin`?

**Comment by anhnhoktvn** [comment]
![screenshot_2018-03-21_09-55-52](https://user-images.githubusercontent.com/2435820/37692884-45626b74-2cee-11e8-8b9a-11d6a24b69d6.png)
![screenshot_2018-03-21_09-56-23](https://user-images.githubusercontent.com/2435820/37692889-49f97d08-2cee-11e8-9f54-95ff613c3044.png)

**Comment by Cretezy** [comment]
I see the problem. npm isn't locally linking the bin. I'll have a fix within an hour or so

**Comment by Cretezy** [comment]
https://github.com/Cretezy/Noderize/commit/7dcccb5b47bff17f17ebc83d478dc1b57f084d82.

Published v0.4.6. Let me know if this changes. You'll just need to change the values in your `package.json` and `npm i`.

**Comment by anhnhoktvn** [comment]
Thanks! it works!

**Comment by Cretezy** [comment]
Perfect! Thanks for the report, this was a tricky one. I basically make it fall over to the root's `node_modules` if it can't find the first one.
